-- copied/adapted from https://github.com/kungfusheep/mfd.nvim.git
-- MFD Amber: Classic amber phosphor CRT terminal
-- Dark background with warm glowing amber text

local M = {}

local c = {
  bg       = '#0F0C08',  -- near black with warm undertone
  fg       = '#CC9944',  -- warm amber glow
  dim      = '#382818',  -- subtle amber (comments)
  bright   = '#FFBB55',  -- bright amber (emphasis)
  subtle   = '#4A3820',  -- dark amber (line numbers)
  visual   = '#2A1C10',  -- selection
  cursor   = '#1A1408',  -- cursor line
  border   = '#3A2810',  -- window borders
  float_bg = '#141008',  -- floating windows
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Editor
function hl_editor()
    hi('Normal',       { fg = c.fg, bg = c.bg })
    hi('NormalNC',     { fg = c.fg, bg = c.bg })
    hi('NormalFloat',  { fg = c.fg, bg = c.float_bg })
    hi('FloatBorder',  { fg = c.dim, bg = c.float_bg })
    hi('FloatTitle',   { fg = c.fg, bg = c.float_bg, bold = true })
    hi('FloatShadow',  { bg = c.border, blend = 80 })
    hi('FloatShadowThrough', { bg = c.border, blend = 100 })
    hi('Cursor',       { fg = c.bg, bg = c.bright })
    hi('lCursor',      { fg = c.bg, bg = c.bright })
    hi('CursorIM',     { fg = c.bg, bg = c.bright })
    hi('TermCursor',   { fg = c.bg, bg = c.bright })
    hi('TermCursorNC', { fg = c.bg, bg = c.dim })
    hi('CursorNormal',  { fg = c.bg, bg = '#CC9944' })  -- amber, home base
    hi('CursorInsert',  { fg = c.bg, bg = '#FFD070' })  -- hot bright amber, max pop
    hi('CursorVisual',  { fg = c.bg, bg = '#AA7733' })  -- deep amber, selection
    hi('CursorReplace', { fg = c.bg, bg = '#DD7744' })  -- orange-amber, destructive
    hi('CursorCommand', { fg = c.bg, bg = '#CC9944' })  -- same as normal
    hi('CursorLine',   { bg = c.cursor })
    hi('CursorColumn', { bg = c.cursor })
    hi('LineNr',       { fg = c.subtle })
    hi('CursorLineNr', { fg = c.fg, bold = true })
    hi('SignColumn',   { bg = 'NONE' })
    hi('VertSplit',    { fg = c.border, bg = c.bg })
    hi('WinSeparator', { fg = c.border, bg = c.bg })
    hi('StatusLine',   { fg = c.fg, bg = c.cursor, bold = true })
    hi('StatusLineNC', { fg = c.dim, bg = c.cursor })
    hi('TabLine',      { fg = c.dim, bg = c.cursor })
    hi('TabLineFill',  { bg = c.cursor })
    hi('TabLineSel',   { fg = c.fg, bg = c.bg, bold = true })
    hi('WinBar',       { fg = c.fg, bg = c.bg, bold = true })
    hi('WinBarNC',     { fg = c.dim, bg = c.bg })
    hi('Pmenu',        { fg = c.fg, bg = c.float_bg })
    hi('PmenuSel',     { fg = c.bg, bg = c.fg, bold = true })
    hi('PmenuSbar',    { bg = c.float_bg })
    hi('PmenuThumb',   { bg = c.dim })
    hi('PmenuMatch',   { fg = c.fg, bold = true })
    hi('PmenuMatchSel', { fg = c.bg, bold = true })
    hi('PmenuExtra',   { fg = c.dim })
    hi('PmenuExtraSel', { fg = c.bg, bg = c.fg })
    hi('Visual',       { bg = c.visual })
    hi('VisualNOS',    { bg = c.visual })
    hi('Search',       { fg = c.bg, bg = c.fg, bold = true })
    hi('IncSearch',    { fg = c.bg, bg = c.bright, bold = true })
    hi('CurSearch',    { fg = c.bg, bg = c.bright, bold = true })
    hi('MatchParen',   { fg = c.bright, bold = true, underline = true })
    hi('Folded',       { fg = c.dim, bg = c.cursor, italic = true })
    hi('FoldColumn',   { fg = c.dim, bg = 'NONE' })
    hi('NonText',      { fg = c.subtle })
    hi('SpecialKey',   { fg = c.subtle })
    hi('Whitespace',   { fg = c.subtle })
    hi('EndOfBuffer',  { fg = c.subtle })
    hi('Directory',    { fg = c.fg, bold = true })
    hi('Title',        { fg = c.fg, bold = true })
    hi('ErrorMsg',     { fg = c.fg, bg = c.bg, bold = true, underline = true })
    hi('WarningMsg',   { fg = c.fg, bold = true })
    hi('MoreMsg',      { fg = c.fg, bold = true })
    hi('ModeMsg',      { fg = c.fg, bold = true })
    hi('Question',     { fg = c.fg, bold = true })
    hi('WildMenu',     { fg = c.bg, bg = c.fg })
    hi('QuickFixLine', { bg = c.cursor, bold = true })
    hi('Conceal',      { fg = c.dim })
    hi('SpellBad',     { undercurl = true, sp = c.fg })
    hi('SpellCap',     { undercurl = true, sp = c.dim })
    hi('SpellRare',    { undercurl = true, sp = c.dim })
    hi('SpellLocal',   { undercurl = true, sp = c.dim })
    hi('DiffAdd',      { bg = '#1A1A08' })
    hi('DiffChange',   { bg = '#1A1408' })
    hi('DiffDelete',   { fg = c.dim, bg = '#1A0808' })
    hi('DiffText',     { bg = '#2A2010', bold = true })
end

function hl_syntax()
    -- syntax: monotone with decoration
    hi('Comment',      { fg = c.dim, italic = true })
    hi('Constant',     { fg = c.fg })
    hi('String',       { fg = c.fg, italic = true })
    hi('Character',    { fg = c.fg })
    hi('Number',       { fg = c.fg })
    hi('Boolean',      { fg = c.fg, bold = true })
    hi('Float',        { fg = c.fg })
    hi('Identifier',   { fg = c.fg })
    hi('Function',     { fg = c.fg, bold = true })
    hi('Statement',    { fg = c.bright, bold = true })
    hi('Conditional',  { fg = c.bright, bold = true })
    hi('Repeat',       { fg = c.bright, bold = true })
    hi('Label',        { fg = c.fg, bold = true })
    hi('Operator',     { fg = c.fg })
    hi('Keyword',      { fg = c.bright, bold = true })
    hi('Exception',    { fg = c.bright, bold = true })
    hi('PreProc',      { fg = c.fg, bold = true })
    hi('Include',      { fg = c.fg, bold = true })
    hi('Define',       { fg = c.fg, bold = true })
    hi('Macro',        { fg = c.fg, bold = true })
    hi('PreCondit',    { fg = c.fg, bold = true })
    hi('Type',         { fg = c.fg, underline = true })
    hi('StorageClass', { fg = c.fg, bold = true })
    hi('Structure',    { fg = c.fg, underline = true })
    hi('Typedef',      { fg = c.fg, underline = true })
    hi('Special',      { fg = c.fg })
    hi('SpecialChar',  { fg = c.fg, bold = true })
    hi('Tag',          { fg = c.fg, underline = true })
    hi('Delimiter',    { fg = c.fg })
    hi('SpecialComment', { fg = c.dim, bold = true, italic = true })
    hi('Debug',        { fg = c.fg })
    hi('Underlined',   { fg = c.fg, underline = true })
    hi('Ignore',       { fg = c.subtle })
    hi('Error',        { fg = c.fg, bold = true, underline = true })
    hi('Todo',         { fg = c.bg, bg = c.fg, bold = true })
end

function hl_ts()
    -- Treesitter (same pattern as mfd.lua)
    hi('@variable',           { fg = c.fg })
    hi('@variable.builtin',   { fg = c.fg, italic = true })
    hi('@variable.parameter', { fg = c.fg, italic = true })
    hi('@variable.member',    { fg = c.fg })
    hi('@constant',           { fg = c.fg })
    hi('@constant.builtin',   { fg = c.fg, bold = true })
    hi('@constant.macro',     { fg = c.fg, bold = true })
    hi('@module',             { fg = c.fg })
    hi('@label',              { fg = c.fg, bold = true })
    hi('@string',             { fg = c.fg, italic = true })
    hi('@string.escape',      { fg = c.fg, bold = true })
    hi('@string.special',     { fg = c.fg, bold = true })
    hi('@character',          { fg = c.fg })
    hi('@number',             { fg = c.fg })
    hi('@boolean',            { fg = c.fg, bold = true })
    hi('@float',              { fg = c.fg })
    hi('@function',           { fg = c.fg, bold = true })
    hi('@function.builtin',   { fg = c.fg, bold = true, italic = true })
    hi('@function.call',      { fg = c.fg })
    hi('@function.macro',     { fg = c.fg, bold = true })
    hi('@method',             { fg = c.fg, bold = true })
    hi('@method.call',        { fg = c.fg })
    hi('@constructor',        { fg = c.fg, bold = true })
    hi('@keyword',            { fg = c.bright, bold = true })
    hi('@keyword.function',   { fg = c.bright, bold = true })
    hi('@keyword.operator',   { fg = c.fg })
    hi('@keyword.return',     { fg = c.bright, bold = true })
    hi('@conditional',        { fg = c.bright, bold = true })
    hi('@repeat',             { fg = c.bright, bold = true })
    hi('@exception',          { fg = c.bright, bold = true })
    hi('@include',            { fg = c.fg, bold = true })
    hi('@type',               { fg = c.fg, underline = true })
    hi('@type.builtin',       { fg = c.fg, underline = true })
    hi('@type.definition',    { fg = c.fg, underline = true })
    hi('@type.qualifier',     { fg = c.fg, bold = true })
    hi('@attribute',          { fg = c.fg })
    hi('@field',              { fg = c.fg })
    hi('@property',           { fg = c.fg })
    hi('@parameter',          { fg = c.fg, italic = true })
    hi('@operator',           { fg = c.fg })
    hi('@punctuation',        { fg = c.fg })
    hi('@punctuation.bracket',    { fg = c.fg })
    hi('@punctuation.delimiter',  { fg = c.fg })
    hi('@punctuation.special',    { fg = c.fg, bold = true })
    hi('@comment',            { fg = c.dim, italic = true })
    hi('@comment.documentation', { fg = c.dim, italic = true })
    hi('@tag',                { fg = c.fg, bold = true })
    hi('@tag.attribute',      { fg = c.fg, italic = true })
    hi('@tag.delimiter',      { fg = c.fg })
    hi('@text',               { fg = c.fg })
    hi('@text.strong',        { fg = c.fg, bold = true })
    hi('@text.emphasis',      { fg = c.fg, italic = true })
    hi('@text.underline',     { fg = c.fg, underline = true })
    hi('@text.strike',        { fg = c.fg, strikethrough = true })
    hi('@text.title',         { fg = c.fg, bold = true })
    hi('@text.literal',       { fg = c.fg })
    hi('@text.uri',           { fg = c.fg, underline = true })
    hi('@text.reference',     { fg = c.fg, italic = true })
end

function hl_md()
    -- Markdown headings (render-markdown.nvim)
    hi('RenderMarkdownH1',    { fg = c.bright, bold = true })
    hi('RenderMarkdownH2',    { fg = c.bright, bold = true })
    hi('RenderMarkdownH3',    { fg = c.fg, bold = true })
    hi('RenderMarkdownH4',    { fg = c.fg, bold = true })
    hi('RenderMarkdownH1Bg',  { fg = c.bright, bold = true })
    hi('RenderMarkdownH2Bg',  { fg = c.bright, bold = true })
    hi('RenderMarkdownH3Bg',  { fg = c.fg, bold = true })
    hi('RenderMarkdownH4Bg',  { fg = c.fg, bold = true })
    hi('RenderMarkdownCode',  { bg = c.visual })
    hi('RenderMarkdownCodeInline', { bg = c.visual })
    hi('RenderMarkdownBullet', { fg = c.dim })
    hi('RenderMarkdownTableHead', { fg = c.fg, bold = true })
    hi('RenderMarkdownTableRow',  { fg = c.fg })
    hi('RenderMarkdownSuccess', { fg = c.fg })
    hi('RenderMarkdownInfo',    { fg = c.dim })
    hi('RenderMarkdownHint',    { fg = c.dim, italic = true })
    hi('RenderMarkdownWarn',    { fg = c.fg })
    hi('RenderMarkdownError',   { fg = c.fg, bold = true })
    hi('@markup.heading.1.markdown', { fg = c.bright, bold = true })
    hi('@markup.heading.2.markdown', { fg = c.bright, bold = true })
    hi('@markup.heading.3.markdown', { fg = c.fg, bold = true })
    hi('@markup.heading.4.markdown', { fg = c.fg, bold = true })
    hi('@markup.raw.markdown_inline', { bg = c.visual })
end

function hl_lsp()
    -- LSP Diagnostics
    hi('DiagnosticError',     { fg = c.fg, bold = true })
    hi('DiagnosticWarn',      { fg = c.fg })
    hi('DiagnosticInfo',      { fg = c.dim })
    hi('DiagnosticHint',      { fg = c.dim, italic = true })
    hi('DiagnosticOk',        { fg = c.dim })
    hi('DiagnosticUnderlineError', { undercurl = true, sp = c.fg })
    hi('DiagnosticUnderlineWarn',  { undercurl = true, sp = c.dim })
    hi('DiagnosticUnderlineInfo',  { undercurl = true, sp = c.subtle })
    hi('DiagnosticUnderlineHint',  { undercurl = true, sp = c.subtle })
    hi('DiagnosticUnderlineOk',    { undercurl = true, sp = c.subtle })
    hi('DiagnosticVirtualTextError', { fg = c.fg, bg = c.cursor, bold = true })
    hi('DiagnosticVirtualTextWarn',  { fg = c.fg, bg = c.cursor })
    hi('DiagnosticVirtualTextInfo',  { fg = c.dim, bg = c.cursor })
    hi('DiagnosticVirtualTextHint',  { fg = c.dim, bg = c.cursor, italic = true })
    hi('DiagnosticVirtualTextOk',    { fg = c.dim, bg = c.cursor })
    hi('DiagnosticFloatingError', { fg = c.fg, bold = true })
    hi('DiagnosticFloatingWarn',  { fg = c.fg })
    hi('DiagnosticFloatingInfo',  { fg = c.dim })
    hi('DiagnosticFloatingHint',  { fg = c.dim, italic = true })
    hi('DiagnosticFloatingOk',    { fg = c.dim })
    hi('DiagnosticSignError', { fg = c.fg, bold = true })
    hi('DiagnosticSignWarn',  { fg = c.fg })
    hi('DiagnosticSignInfo',  { fg = c.dim })
    hi('DiagnosticSignHint',  { fg = c.dim })
    hi('DiagnosticSignOk',    { fg = c.dim })

    -- LSP References & Hints
    hi('LspReferenceText',    { bg = c.cursor })
    hi('LspReferenceRead',    { bg = c.cursor })
    hi('LspReferenceWrite',   { bg = c.cursor, bold = true })
    hi('LspSignatureActiveParameter', { bg = c.visual, bold = true })
    hi('LspCodeLens',         { fg = c.dim, italic = true })
    hi('LspCodeLensSeparator', { fg = c.dim })
    hi('LspInlayHint',        { fg = c.dim, bg = c.cursor, italic = true })
    hi('LspInfoBorder',       { fg = c.dim, bg = c.float_bg })

    -- Semantic tokens (LSP)
    hi('@lsp.type.class',         { fg = c.fg, underline = true })
    hi('@lsp.type.struct',        { fg = c.fg, underline = true })
    hi('@lsp.type.interface',     { fg = c.fg, underline = true })
    hi('@lsp.type.parameter',     { fg = c.fg, italic = true })
    hi('@lsp.type.variable',      { fg = c.fg })
    hi('@lsp.type.property',      { fg = c.fg })
    hi('@lsp.type.function',      { fg = c.fg, bold = true })
    hi('@lsp.type.method',        { fg = c.fg, bold = true })
    hi('@lsp.type.keyword',       { fg = c.bright, bold = true })
    hi('@lsp.type.namespace',     { fg = c.fg })
    hi('@lsp.type.type',          { fg = c.fg, underline = true })
    hi('@lsp.type.typeParameter', { fg = c.fg, italic = true })
    hi('@lsp.mod.defaultLibrary', { italic = true })
end

function M.setup()
   if vim.g.colors_name then
       vim.cmd("hl clear")
   end
   vim.g.colors_name = 'mfd-amber'
   hl_editor()
   hl_syntax()
   hl_ts()
   hl_lsp()
   hl_md()
end

return M
